on:
  release:
    types: [created]

name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        uses: actions/setup-node@v1
        with:
          node-version: 16
      -
        run: npm install
      -
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
